## Now we'll see how to clean data!

In [1]:
import numpy as np
import pandas as pd

In [66]:
df=pd.read_csv("data.csv")
print(df)

# df.isnull().sum()

   employee_id         name   age department salary       city  \
0       EMP001  Aman Sharma  22.0         IT  40000      Delhi
1       EMP002   Riya Verma  24.0         HR  45000    Lucknow
2       EMP003  Rahul Singh  23.0        it   50000     Indore
3       EMP004  Priya Gupta  25.0    Finance  55000     Bhopal
4       EMP005  Karan Mehta  21.0  Marketing  35000     Jaipur
..         ...          ...   ...        ...    ...        ...
95      EMP096  Nikhil Bose  20.0      Sales  68000     Jaipur
96      EMP097   Rohan Bhat  26.0         HR  28000     Indore
97      EMP098   Meera Nair  40.0         HR  40000  New Delhi
98      EMP099   Kavya Shah  20.0      Sales  68000  Hyderabad
99      EMP100     Diya Sen  53.0  Marketing  75000     Bhopal

                     email joining_date
0    aman.sharma@gmail.com   2024-01-15
1     riya.verma@gmail.com   2023-11-02
2    rahul.singh@gmail.com   2024/02/10
3    priya.gupta@gmail.com   2022-07-21
4    karan.mehta@gmail.com   2024-03-12
..                     ...          ...
95   nikhil.bose@yahoo.com   2023-09-22
96    rohan.bhat@yahoo.com   2022-03-08
97  meera.nair@outlook.com   2023-09-22
98    kavya.shah@gmail.com   2022-12-01
99    diya.sen@company.com   2021-06-14

[100 rows x 8 columns]

### dropping the null values:

In [67]:
#Drop the rows that have null values
# df=df.dropna()
# print(df.isnull().sum())
# print(df)


#drop null values by name
# df=df.dropna(subset=["city","age","email","salary","employee_id"])
# df.isnull().sum()
# print(df)

### Filling null values:

In [88]:
df = pd.read_csv("data.csv")

df["age"] = df["age"].fillna(df["age"].mean())
df.isnull().sum()

employee_id     1
name            0
age             0
department      0
salary          2
city            1
email           2
joining_date    0
dtype: int64

In [106]:
df["salary"]=pd.to_numeric(df["salary"], errors='coerce')
df["salary"]=df["salary"].fillna(df["salary"].median())
df.isnull().sum()

employee_id     1
name            0
age             0
department      0
salary          0
city            1
email           2
joining_date    0
dtype: int64

In [121]:
#using Value Count
df["department"].value_counts()

#filling with mode
df["department"]= df["department"].fillna(df["department"].mode()[0])
df.isnull().sum()
(df.duplicated(subset="employee_id")).sum()
df.drop_duplicates(subset="employee_id", keep='first')

,employee_id,name,age,department,salary,city,email,joining_date
0,EMP001,Aman Sharma,22.0,IT,40000.0,Delhi,aman.sharma@gmail.com,2024-01-15
1,EMP002,Riya Verma,24.0,HR,45000.0,Lucknow,riya.verma@gmail.com,2023-11-02
2,EMP003,Rahul Singh,23.0,it,50000.0,Indore,rahul.singh@gmail.com,2024/02/10
3,EMP004,Priya Gupta,25.0,Finance,55000.0,Bhopal,priya.gupta@gmail.com,2022-07-21
4,EMP005,Karan Mehta,21.0,Marketing,35000.0,Jaipur,karan.mehta@gmail.com,2024-03-12
...,...,...,...,...,...,...,...,...
95,EMP096,Nikhil Bose,20.0,Sales,68000.0,Jaipur,nikhil.bose@yahoo.com,2023-09-22
96,EMP097,Rohan Bhat,26.0,HR,28000.0,Indore,rohan.bhat@yahoo.com,2022-03-08
97,EMP098,Meera Nair,40.0,HR,40000.0,New Delhi,meera.nair@outlook.com,2023-09-22
98,EMP099,Kavya Shah,20.0,Sales,68000.0,Hyderabad,kavya.shah@gmail.com,2022-12-01
99,EMP100,Diya Sen,53.0,Marketing,75000.0,Bhopal,diya.sen@company.com,2021-06-14

In [123]:
#Renaming Cloumns
df.rename(columns={"employee_id" :" id " })

,id,name,age,department,salary,city,email,joining_date
0,EMP001,Aman Sharma,22.0,IT,40000.0,Delhi,aman.sharma@gmail.com,2024-01-15
1,EMP002,Riya Verma,24.0,HR,45000.0,Lucknow,riya.verma@gmail.com,2023-11-02
2,EMP003,Rahul Singh,23.0,it,50000.0,Indore,rahul.singh@gmail.com,2024/02/10
3,EMP004,Priya Gupta,25.0,Finance,55000.0,Bhopal,priya.gupta@gmail.com,2022-07-21
4,EMP005,Karan Mehta,21.0,Marketing,35000.0,Jaipur,karan.mehta@gmail.com,2024-03-12
...,...,...,...,...,...,...,...,...
95,EMP096,Nikhil Bose,20.0,Sales,68000.0,Jaipur,nikhil.bose@yahoo.com,2023-09-22
96,EMP097,Rohan Bhat,26.0,HR,28000.0,Indore,rohan.bhat@yahoo.com,2022-03-08
97,EMP098,Meera Nair,40.0,HR,40000.0,New Delhi,meera.nair@outlook.com,2023-09-22
98,EMP099,Kavya Shah,20.0,Sales,68000.0,Hyderabad,kavya.shah@gmail.com,2022-12-01
99,EMP100,Diya Sen,53.0,Marketing,75000.0,Bhopal,diya.sen@company.com,2021-06-14